services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    container_name: flwr_server
    ports:
      - "8080:8080"
    volumes:
      - ./data:/app/data
      - ./performance:/app/performance
      - ./configuration:/app/configuration
      - ./model_weights:/app/model_weights
      - .:/app
      - /var/run/docker.sock:/var/run/docker.sock 
    environment:
      DOCKER_HOST_IP: host.docker.internal
      NUM_ROUNDS: ${NUM_ROUNDS}
    networks:
      - flwr_network
    deploy:
      resources:
        limits:
          cpus: '0.5'   

  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    labels:
      - "type=client"
    depends_on:
      - server
    networks:
      - flwr_network
    volumes:
      - ./data:/app/data
      - ./performance:/app/performance
      - ./configuration:/app/configuration
      - ./model_weights:/app/model_weights
    environment:
      - SERVER_ADDRESS=server:8080
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: '4g'
    command: sh -c "sleep 2 && python client.py"

networks:
  flwr_network:
    driver: bridge
