# Dockerfile.agent
FROM python:3.12-slim

# Set the environment variable to avoid buffering issues
ENV PYTHONUNBUFFERED=1

# Installation of the libraries
RUN apt-get update && apt-get install -y --no-install-recommends \
    python3-tk \
 && rm -rf /var/lib/apt/lists/*

# Create the working directory
WORKDIR /app

# Copy the client code
COPY client.py /app/client.py
COPY server.py /app/server.py
COPY taskA.py /app/taskA.py
COPY adaptation.py /app/adaptation.py
COPY agent.py /app/agent.py
COPY configuration/ /app/configuration/
COPY performance/ /app/performance/

# Create the folder for data
RUN mkdir -p data

# Execution command
CMD ["python", "agent.py"]
