services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    container_name: flwr_server
    ports:
      - "8080:8080"
    volumes:
      - ./performance:/app/performance
      - /var/run/docker.sock:/var/run/docker.sock 
    environment:
      DOCKER_HOST_IP: host.docker.internal
      NUM_ROUNDS: ${NUM_ROUNDS}
    networks:
      - flwr_network
    deploy:
      resources:
        limits:
          cpus: '1'   

  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    labels:
      - "type=client"
    depends_on:
      - server
    networks:
      - flwr_network
    volumes:
      - ./data:/app/data
    deploy:
      resources:
        limits:
          cpus: '1'
    command: sh -c "sleep 5 && python client.py"

networks:
  flwr_network:
    driver: bridge

volumes:
  grafana_data:
    driver: local