services:
  server:
    build:
      context: /Users/ivan/Desktop/AP4Fed/Docker
      dockerfile: /Users/ivan/Desktop/AP4Fed/Docker/Dockerfile.server
    container_name: flwr_server
    ports:
    - 8080:8080
    volumes:
    - /Users/ivan/Desktop/AP4Fed/Docker/data:/app/data
    - /Users/ivan/Desktop/AP4Fed/Docker/logs:/app/logs
    - /Users/ivan/Desktop/AP4Fed/Docker/performance:/app/performance
    - /Users/ivan/Desktop/AP4Fed/Docker/configuration:/app/configuration
    - /Users/ivan/Desktop/AP4Fed/Docker/model_weights:/app/model_weights
    - /Users/ivan/Desktop/AP4Fed/Docker:/app
    - /var/run/docker.sock:/var/run/docker.sock
    environment:
      DOCKER_HOST_IP: host.docker.internal
      NUM_ROUNDS: '10'
      AGENT_LOG_TO_FILE: '0'
      AGENT_LOG_FILE: /dev/null
    networks:
    - flwr_network
    deploy:
      resources:
        limits:
          cpus: '0.5'
    image: ap4fed_server:latest
    extra_hosts:
    - host.docker.internal:host-gateway
  client1:
    image: ap4fed_client:latest
    build:
      context: /Users/ivan/Desktop/AP4Fed/Docker
      dockerfile: /Users/ivan/Desktop/AP4Fed/Docker/Dockerfile.client
    labels:
    - type=client
    depends_on:
    - server
    networks:
    - flwr_network
    volumes:
    - /Users/ivan/Desktop/AP4Fed/Docker/data:/app/data
    - /Users/ivan/Desktop/AP4Fed/Docker/performance:/app/performance
    - /Users/ivan/Desktop/AP4Fed/Docker/configuration:/app/configuration
    - /Users/ivan/Desktop/AP4Fed/Docker/model_weights:/app/model_weights
    environment:
      NUM_ROUNDS: '10'
      NUM_CPUS: '5'
      NUM_RAM: 2g
      SERVER_ADDRESS: server:8080
      CPUSET_CPUS: 0-4
      CLIENT_ID: '1'
      AGENT_LOG_TO_FILE: '0'
      AGENT_LOG_FILE: /dev/null
    command: sh -c "sleep 5 && python client.py"
    container_name: Client1
    cpus: 5.0
    cpuset: 0-4
    mem_limit: 2g
    extra_hosts:
    - host.docker.internal:host-gateway
  client2:
    image: ap4fed_client:latest
    build:
      context: /Users/ivan/Desktop/AP4Fed/Docker
      dockerfile: /Users/ivan/Desktop/AP4Fed/Docker/Dockerfile.client
    labels:
    - type=client
    depends_on:
    - server
    networks:
    - flwr_network
    volumes:
    - /Users/ivan/Desktop/AP4Fed/Docker/data:/app/data
    - /Users/ivan/Desktop/AP4Fed/Docker/performance:/app/performance
    - /Users/ivan/Desktop/AP4Fed/Docker/configuration:/app/configuration
    - /Users/ivan/Desktop/AP4Fed/Docker/model_weights:/app/model_weights
    environment:
      NUM_ROUNDS: '10'
      NUM_CPUS: '5'
      NUM_RAM: 2g
      SERVER_ADDRESS: server:8080
      CPUSET_CPUS: 5-9
      CLIENT_ID: '2'
      AGENT_LOG_TO_FILE: '0'
      AGENT_LOG_FILE: /dev/null
    command: sh -c "sleep 5 && python client.py"
    container_name: Client2
    cpus: 5.0
    cpuset: 5-9
    mem_limit: 2g
    extra_hosts:
    - host.docker.internal:host-gateway
  client3:
    image: ap4fed_client:latest
    build:
      context: /Users/ivan/Desktop/AP4Fed/Docker
      dockerfile: /Users/ivan/Desktop/AP4Fed/Docker/Dockerfile.client
    labels:
    - type=client
    depends_on:
    - server
    networks:
    - flwr_network
    volumes:
    - /Users/ivan/Desktop/AP4Fed/Docker/data:/app/data
    - /Users/ivan/Desktop/AP4Fed/Docker/performance:/app/performance
    - /Users/ivan/Desktop/AP4Fed/Docker/configuration:/app/configuration
    - /Users/ivan/Desktop/AP4Fed/Docker/model_weights:/app/model_weights
    environment:
      NUM_ROUNDS: '10'
      NUM_CPUS: '5'
      NUM_RAM: 2g
      SERVER_ADDRESS: server:8080
      CPUSET_CPUS: 0-3,10
      CLIENT_ID: '3'
      AGENT_LOG_TO_FILE: '0'
      AGENT_LOG_FILE: /dev/null
    command: sh -c "sleep 5 && python client.py"
    container_name: Client3
    cpus: 5.0
    cpuset: 0-3,10
    mem_limit: 2g
    extra_hosts:
    - host.docker.internal:host-gateway
  client4:
    image: ap4fed_client:latest
    build:
      context: /Users/ivan/Desktop/AP4Fed/Docker
      dockerfile: /Users/ivan/Desktop/AP4Fed/Docker/Dockerfile.client
    labels:
    - type=client
    depends_on:
    - server
    networks:
    - flwr_network
    volumes:
    - /Users/ivan/Desktop/AP4Fed/Docker/data:/app/data
    - /Users/ivan/Desktop/AP4Fed/Docker/performance:/app/performance
    - /Users/ivan/Desktop/AP4Fed/Docker/configuration:/app/configuration
    - /Users/ivan/Desktop/AP4Fed/Docker/model_weights:/app/model_weights
    environment:
      NUM_ROUNDS: '10'
      NUM_CPUS: '3'
      NUM_RAM: 2g
      SERVER_ADDRESS: server:8080
      CPUSET_CPUS: 4-6
      CLIENT_ID: '4'
      AGENT_LOG_TO_FILE: '0'
      AGENT_LOG_FILE: /dev/null
    command: sh -c "sleep 5 && python client.py"
    container_name: Client4
    cpus: 3.0
    cpuset: 4-6
    mem_limit: 2g
    extra_hosts:
    - host.docker.internal:host-gateway
  client5:
    image: ap4fed_client:latest
    build:
      context: /Users/ivan/Desktop/AP4Fed/Docker
      dockerfile: /Users/ivan/Desktop/AP4Fed/Docker/Dockerfile.client
    labels:
    - type=client
    depends_on:
    - server
    networks:
    - flwr_network
    volumes:
    - /Users/ivan/Desktop/AP4Fed/Docker/data:/app/data
    - /Users/ivan/Desktop/AP4Fed/Docker/performance:/app/performance
    - /Users/ivan/Desktop/AP4Fed/Docker/configuration:/app/configuration
    - /Users/ivan/Desktop/AP4Fed/Docker/model_weights:/app/model_weights
    environment:
      NUM_ROUNDS: '10'
      NUM_CPUS: '3'
      NUM_RAM: 2g
      SERVER_ADDRESS: server:8080
      CPUSET_CPUS: 7-9
      CLIENT_ID: '5'
      AGENT_LOG_TO_FILE: '0'
      AGENT_LOG_FILE: /dev/null
    command: sh -c "sleep 5 && python client.py"
    container_name: Client5
    cpus: 3.0
    cpuset: 7-9
    mem_limit: 2g
    extra_hosts:
    - host.docker.internal:host-gateway
networks:
  flwr_network:
    driver: bridge
